name: Publish workflow-service image

on:
  workflow_dispatch:

env:
  IMAGE_NAME: ballerine-backoffice
  AWS_REGION: eu-west-2 # set this to your preferred AWS region, e.g. us-west-1
  ECR_REPOSITORY: ballerine-backoffice_staging # set this to your Amazon ECR repository name


jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install jq
        run: sudo apt-get install jq

      #      - name: Check if the tag name contains "workflows-service"
      #        run: |
      #          TAG_NAME=${{ github.event.release.tag_name }}
      #          if [[ "$TAG_NAME" != *"workflows-service"* ]]; then
      #            echo "Release tag does not contain 'workflows-service'. Skipping this workflow."
      #            exit 1
      #          fi
      #        continue-on-error: false

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::229340442280:role/ballerine-gh-actions-staging-role
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Get package version from package.json
        id: get_version
        run: |
          PACKAGE_VERSION=$(jq -r '.version' services/workflows-service/package.json)
          echo "::set-output name=version::$PACKAGE_VERSION"

      - name: Print the version
        run: echo "The version was ${{ steps.get_version.outputs.version }}"

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          IMAGE_TAG: latest
        with:
          images: ${{ env.ECR_REGISTRY }}/${{ env.IMAGE_NAME }}/${{ env.IMAGE_TAG }}
          tags: |
            type=semver,pattern={{version}},value=v${{ steps.get_version.outputs.version }}

      - name: Build and push Docker image
        uses: docker/build-push-action@f2a1d5e99d037542a71f64918e516c093c6f3fc4
        with:
          context: services/workflows-service
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
